Created demo
kaazing/kaazing.io-demo-stocks pull request #1
Opened 2018-09-21 11:01 UTC by pgodfrey

2018-09-21 15:17 UTC, robinzimmermann commented
- Make the column headers for **Symbol** and **Name** left-aligned to match the data.

- Add some padding to big background rectangle so the symbol names on the right and the the change prices on the right don't look so squashed up against the sides.

- Can the downward facing red triangles be moved down a pixel or two so they align with the top of the numbers better? Like the baseline of the green triangles are aligned with the baseline of the green numbers.

- Tab title should not say "React App"

- Change the favicon to the attached image:

![favicon-32x32](https://user-images.githubusercontent.com/725660/45889928-85009a80-bd76-11e8-8fc9-1af8a00d11df.png)

- Heading on the page should have a lowercase `k` for `kaazing.io`.

- The Javascript console has an error. Is it possible to eliminate that?

- See other comments inline, in the review (in the README file)

2018-09-21 15:25 UTC, robinzimmermann requested changes
- Make the column headers for **Symbol** and **Name** left-aligned to match the data.

- Add some padding to big background rectangle so the symbol names on the right and the the change prices on the right don't look so squashed up against the sides.

- Can the downward facing red triangles be moved down a pixel or two so they align with the top of the numbers better? Like the baseline of the green triangles are aligned with the baseline of the green numbers.

- Tab title should not say "React App"

- Change the favicon to the attached image:

![favicon-32x32](https://user-images.githubusercontent.com/725660/45889928-85009a80-bd76-11e8-8fc9-1af8a00d11df.png)

- Heading on the page should have a lowercase `k` for `kaazing.io`.

- The Javascript console has an error. Is it possible to eliminate that?

- See other comments inline, in the review

- We need to add a license
    - Add an appropriate license that gives permission for people to use without attribution.
    - Add a Kaazing copyright to key source files.

2018-09-21 15:25 UTC, robinzimmermann commented on README.md
> +
Provide instructions for building, e.g. `yarn` and / or `npm install`.

2018-09-21 15:25 UTC, robinzimmermann commented on README.md
> +See the section about [running tests](#running-tests) for more information.
There is no "running tests" section, the link doesn't work.

2018-09-21 15:25 UTC, robinzimmermann commented on package.json
> +  "name": "my-app",
Put correct values in `package.json` for `name` and `description`.

2018-09-21 15:25 UTC, robinzimmermann commented on public/manifest.json
> +{
Files from the `public` directory should not be checked in, right?

2018-09-21 15:25 UTC, robinzimmermann commented on src/App.css
> +body {
Do we need two `body` tags right next to each other?

2018-09-21 15:25 UTC, robinzimmermann commented on src/App.js
> +    let eventSource = new EventSource("https://a8uofb8l.streaming.kaazing.io/topic/sandbox.stocks");
The public endpoint `https://streams.kaazing.net/sandbox/stocks` is now available to use here.

2018-09-22 18:34 UTC, pgodfrey commented on public/manifest.json
> +{
I think they do need to be checked in - it contains the index.html, manifest and favicon

2019-02-11 22:35 UTC, merged